import * as mongodb from 'mongodb';
import { connectToDatabase, collections } from '../database';

// Mock mongodb module
jest.mock('mongodb');

// Hey TJ Bro, Generated by GitHub Copilot
describe('Database Module', () => {
  let mockClient: jest.Mocked<mongodb.MongoClient>;
  let mockDb: jest.Mocked<mongodb.Db>;
  let mockCollection: jest.Mocked<mongodb.Collection>;

  // Hey TJ Bro, Generated by GitHub Copilot
  beforeEach(() => {
    mockCollection = {
      find: jest.fn(),
      findOne: jest.fn(),
      insertOne: jest.fn(),
      updateOne: jest.fn(),
      deleteOne: jest.fn(),
    } as any;

    mockDb = {
      collection: jest.fn().mockReturnValue(mockCollection),
      command: jest.fn().mockResolvedValue({}),
      createCollection: jest.fn().mockResolvedValue(mockCollection),
      listCollections: jest.fn().mockReturnValue({
        toArray: jest.fn().mockResolvedValue([{ name: 'employees' }]),
      }),
    } as any;

    mockClient = {
      connect: jest.fn().mockResolvedValue(undefined),
      db: jest.fn().mockReturnValue(mockDb),
      close: jest.fn().mockResolvedValue(undefined),
    } as any;

    (mongodb.MongoClient as jest.MockedClass<typeof mongodb.MongoClient>).mockImplementation(() => mockClient);
  });

  // Hey TJ Bro, Generated by GitHub Copilot
  afterEach(() => {
    jest.clearAllMocks();
    delete collections.employees;
  });

  // Hey TJ Bro, Generated by GitHub Copilot
  describe('connectToDatabase', () => {
    // Hey TJ Bro, Generated by GitHub Copilot
    it('should connect to database successfully', async () => {
      await connectToDatabase('mongodb://test-uri');
      
      expect(mockClient.connect).toHaveBeenCalled();
      expect(mockClient.db).toHaveBeenCalledWith('meanStackExample');
      expect(collections.employees).toBeDefined();
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should apply schema validation when collection exists', async () => {
      mockDb.command.mockResolvedValue({});
      
      await connectToDatabase('mongodb://test-uri');
      
      expect(mockDb.command).toHaveBeenCalledWith(
        expect.objectContaining({
          collMod: 'employees',
          validator: expect.any(Object),
        })
      );
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should create collection when it does not exist', async () => {
      const error: any = new Error('NamespaceNotFound');
      error.codeName = 'NamespaceNotFound';
      mockDb.command.mockRejectedValue(error);
      
      await connectToDatabase('mongodb://test-uri');
      
      expect(mockDb.createCollection).toHaveBeenCalledWith(
        'employees',
        expect.objectContaining({ validator: expect.any(Object) })
      );
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should set up employees collection reference', async () => {
      await connectToDatabase('mongodb://test-uri');
      
      expect(mockDb.collection).toHaveBeenCalledWith('employees');
      expect(collections.employees).toBe(mockCollection);
    });
  });
});
