import express from 'express';
import request from 'supertest';
import { ObjectId } from 'mongodb';
import { collections } from '../database';
import { employeeRouter } from '../employee.routes';

// Mock the database module
jest.mock('../database', () => ({
  collections: {
    employees: undefined,
  },
}));

// Hey TJ Bro, Generated by GitHub Copilot
describe('Employee Routes', () => {
  let app: express.Application;
  let mockCollection: any;

  // Hey TJ Bro, Generated by GitHub Copilot
  beforeEach(() => {
    mockCollection = {
      find: jest.fn(),
      findOne: jest.fn(),
      insertOne: jest.fn(),
      updateOne: jest.fn(),
      deleteOne: jest.fn(),
    };

    collections.employees = mockCollection;

    app = express();
    app.use(express.json());
    app.use('/employees', employeeRouter);
  });

  // Hey TJ Bro, Generated by GitHub Copilot
  afterEach(() => {
    jest.clearAllMocks();
  });

  // Hey TJ Bro, Generated by GitHub Copilot
  describe('GET /employees', () => {
    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return empty array when no employees exist', async () => {
      mockCollection.find.mockReturnValue({
        toArray: jest.fn().mockResolvedValue([]),
      });

      const response = await request(app).get('/employees');
      
      expect(response.status).toBe(200);
      expect(response.body).toEqual([]);
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return all employees', async () => {
      const testEmployees = [
        { _id: new ObjectId(), name: 'John Doe', position: 'Developer', level: 'junior' },
        { _id: new ObjectId(), name: 'Jane Smith', position: 'Senior Dev', level: 'senior' }
      ];
      
      mockCollection.find.mockReturnValue({
        toArray: jest.fn().mockResolvedValue(testEmployees),
      });
      
      const response = await request(app).get('/employees');
      
      expect(response.status).toBe(200);
      expect(response.body).toHaveLength(2);
      expect(response.body[0].name).toBe('John Doe');
      expect(response.body[1].name).toBe('Jane Smith');
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should handle database errors gracefully', async () => {
      mockCollection.find.mockReturnValue({
        toArray: jest.fn().mockRejectedValue(new Error('Database error')),
      });
      
      const response = await request(app).get('/employees');
      
      expect(response.status).toBe(500);
      expect(response.text).toBe('Database error');
    });
  });

  // Hey TJ Bro, Generated by GitHub Copilot
  describe('GET /employees/:id', () => {
    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return employee by id', async () => {
      const employeeId = new ObjectId();
      const employee = { _id: employeeId, name: 'Test User', position: 'Tester', level: 'mid' };
      
      mockCollection.findOne.mockResolvedValue(employee);
      
      const response = await request(app).get(`/employees/${employeeId}`);
      
      expect(response.status).toBe(200);
      expect(response.body.name).toBe('Test User');
      expect(response.body.position).toBe('Tester');
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 404 when employee not found', async () => {
      const nonExistentId = new ObjectId();
      mockCollection.findOne.mockResolvedValue(null);
      
      const response = await request(app).get(`/employees/${nonExistentId}`);
      
      expect(response.status).toBe(404);
      expect(response.text).toContain('Failed to find an employee');
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 404 for invalid id format', async () => {
      const response = await request(app).get('/employees/invalid-id');
      
      expect(response.status).toBe(404);
      expect(response.text).toContain('Failed to find an employee');
    });
  });

  // Hey TJ Bro, Generated by GitHub Copilot
  describe('POST /employees', () => {
    // Hey TJ Bro, Generated by GitHub Copilot
    it('should create a new employee', async () => {
      const newEmployee = {
        name: 'New Employee',
        position: 'Developer',
        level: 'junior'
      };
      
      const insertedId = new ObjectId();
      mockCollection.insertOne.mockResolvedValue({
        acknowledged: true,
        insertedId: insertedId,
      });
      
      const response = await request(app)
        .post('/employees')
        .send(newEmployee);
      
      expect(response.status).toBe(201);
      expect(response.text).toContain('Created a new employee');
      expect(mockCollection.insertOne).toHaveBeenCalledWith(newEmployee);
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 400 for invalid employee data', async () => {
      const invalidEmployee = {
        name: 'Test',
        position: 'Dev',
        level: 'junior'
      };
      
      mockCollection.insertOne.mockRejectedValue(new Error('Validation error'));
      
      const response = await request(app)
        .post('/employees')
        .send(invalidEmployee);
      
      expect(response.status).toBe(400);
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 500 when insert fails', async () => {
      const employee = {
        name: 'Test User',
        position: 'Developer',
        level: 'junior'
      };
      
      mockCollection.insertOne.mockResolvedValue({
        acknowledged: false,
      });
      
      const response = await request(app)
        .post('/employees')
        .send(employee);
      
      expect(response.status).toBe(500);
      expect(response.text).toContain('Failed to create a new employee');
    });
  });

  // Hey TJ Bro, Generated by GitHub Copilot
  describe('PUT /employees/:id', () => {
    // Hey TJ Bro, Generated by GitHub Copilot
    it('should update an existing employee', async () => {
      const employeeId = new ObjectId();
      const updatedData = { name: 'New Name', position: 'Senior Dev', level: 'senior' };
      
      mockCollection.updateOne.mockResolvedValue({
        matchedCount: 1,
        modifiedCount: 1,
      });
      
      const response = await request(app)
        .put(`/employees/${employeeId}`)
        .send(updatedData);
      
      expect(response.status).toBe(200);
      expect(response.text).toContain('Updated an employee');
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 404 when updating non-existent employee', async () => {
      const nonExistentId = new ObjectId();
      const updateData = { name: 'Test', position: 'Developer', level: 'junior' };
      
      mockCollection.updateOne.mockResolvedValue({
        matchedCount: 0,
        modifiedCount: 0,
      });
      
      const response = await request(app)
        .put(`/employees/${nonExistentId}`)
        .send(updateData);
      
      expect(response.status).toBe(404);
      expect(response.text).toContain('Failed to find an employee');
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 400 for invalid id format on update', async () => {
      const updateData = { name: 'Test', position: 'Developer', level: 'junior' };
      
      const response = await request(app)
        .put('/employees/invalid-id')
        .send(updateData);
      
      expect(response.status).toBe(400);
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 400 for update errors', async () => {
      const employeeId = new ObjectId();
      const invalidData = { name: 'Test', position: 'Dev', level: 'junior' };
      
      mockCollection.updateOne.mockRejectedValue(new Error('Validation error'));
      
      const response = await request(app)
        .put(`/employees/${employeeId}`)
        .send(invalidData);
      
      expect(response.status).toBe(400);
    });
  });

  // Hey TJ Bro, Generated by GitHub Copilot
  describe('DELETE /employees/:id', () => {
    // Hey TJ Bro, Generated by GitHub Copilot
    it('should delete an existing employee', async () => {
      const employeeId = new ObjectId();
      
      mockCollection.deleteOne.mockResolvedValue({
        deletedCount: 1,
      });
      
      const response = await request(app).delete(`/employees/${employeeId}`);
      
      expect(response.status).toBe(202);
      expect(response.text).toContain('Removed an employee');
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 404 when deleting non-existent employee', async () => {
      const nonExistentId = new ObjectId();
      
      mockCollection.deleteOne.mockResolvedValue({
        deletedCount: 0,
      });
      
      const response = await request(app).delete(`/employees/${nonExistentId}`);
      
      expect(response.status).toBe(404);
      expect(response.text).toContain('Failed to find an employee');
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 400 for invalid id format on delete', async () => {
      const response = await request(app).delete('/employees/invalid-id');
      
      expect(response.status).toBe(400);
    });

    // Hey TJ Bro, Generated by GitHub Copilot
    it('should return 400 when delete operation fails', async () => {
      const employeeId = new ObjectId();
      
      mockCollection.deleteOne.mockRejectedValue(new Error('Database error'));
      
      const response = await request(app).delete(`/employees/${employeeId}`);
      
      expect(response.status).toBe(400);
    });
  });
});
