import * as mongodb from "mongodb";
import { Employee } from "./employee";

export const collections: {
    employees?: mongodb.Collection<Employee>;
} = {};

let isCosmosDB = false;

// Generated by GitHub Copilot - Validiert Employee-Daten auf Client-Seite für Cosmos DB
export const validateEmployee = (employee: unknown): employee is Employee => {
    if (!employee || typeof employee !== 'object') {
        throw new Error('Employee must be an object');
    }
    
    const emp = employee as Record<string, unknown>;
    
    if (!emp.name || typeof emp.name !== 'string') {
        throw new Error("'name' is required and must be a string");
    }
    
    if (!emp.position || typeof emp.position !== 'string' || emp.position.length < 5) {
        throw new Error("'position' is required and must be a string with minimum length of 5");
    }
    
    if (!emp.level || !['junior', 'mid', 'senior'].includes(emp.level as string)) {
        throw new Error("'level' is required and must be one of 'junior', 'mid', or 'senior'");
    }
    
    return true;
};

// Generated by GitHub Copilot - Verbindet zur Datenbank (MongoDB oder Azure Cosmos DB)
export const connectToDatabase = async (uri: string) => {
    const client = new mongodb.MongoClient(uri);
    await client.connect();

    const db = client.db("meanStackExample");
    
    // Check if we're using Cosmos DB - use secure hostname validation
    try {
        const url = new URL(uri.replace('mongodb://', 'http://').replace('mongodb+srv://', 'https://'));
        isCosmosDB = url.hostname.endsWith('.mongo.cosmos.azure.com');
    } catch {
        // If URL parsing fails, assume MongoDB (safer default)
        isCosmosDB = false;
    }
    
    // Apply schema validation only for MongoDB (not supported by Cosmos DB MongoDB API)
    if (!isCosmosDB) {
        await applySchemaValidation(db);
    }

    const employeesCollection = db.collection<Employee>("employees");
    collections.employees = employeesCollection;
};

// Generated by GitHub Copilot - Prüft ob Cosmos DB verwendet wird
export const getIsCosmosDB = () => isCosmosDB;

// Update our existing collection with JSON schema validation so we know our documents will always match the shape of our Employee model, even if added elsewhere.
// For more information about schema validation, see this blog series: https://www.mongodb.com/blog/post/json-schema-validation--locking-down-your-model-the-smart-way
async function applySchemaValidation(db: mongodb.Db) {
    const jsonSchema = {
        $jsonSchema: {
            bsonType: "object",
            required: ["name", "position", "level"],
            additionalProperties: false,
            properties: {
                _id: {},
                name: {
                    bsonType: "string",
                    description: "'name' is required and is a string",
                },
                position: {
                    bsonType: "string",
                    description: "'position' is required and is a string",
                    minLength: 5
                },
                level: {
                    bsonType: "string",
                    description: "'level' is required and is one of 'junior', 'mid', or 'senior'",
                    enum: ["junior", "mid", "senior"],
                },
            },
        },
    };

    // Try applying the modification to the collection, if the collection doesn't exist, create it 
   await db.command({
        collMod: "employees",
        validator: jsonSchema
    }).catch(async (error: mongodb.MongoServerError) => {
        if (error.codeName === "NamespaceNotFound") {
            await db.createCollection("employees", {validator: jsonSchema});
        }
    });
}
